import { NextResponse } from 'next/server'
import { generateInvoicePDF } from '@/lib/pdf/utils/pdfGenerator'
import { InvoiceData } from '@/lib/pdf/types/invoice.types'

/**
 * DEBUG ROUTE: Generate a sample invoice PDF
 * Use this to test styling changes in real-time on the server.
 * URL: /api/debug/invoice-preview
 */
export async function GET() {
  try {
    const dummyData: InvoiceData = {
      metadata: {
        invoiceNumber: "SRG-DEBUG-001",
        invoiceDate: new Date().toLocaleDateString('en-AE', { day: 'numeric', month: 'long', year: 'numeric' }),
        orderNumber: "99999",
        paymentMethod: "Stripe (Test Mode)",
        transactionId: "pi_debug_123456789"
      },
      company: {
        name: "Surge Coffee",
        address: "Warehouse #2 – Al Quoz Industrial Area 4",
        city: "Dubai",
        state: "Dubai",
        postcode: "00000",
        country: "UAE",
        email: "hello@surgecoffee.ae",
        phone: "+971 4 000 0000",
        taxId: "TRN: 100123456700003"
      },
      billTo: {
        first_name: "Debug",
        last_name: "User",
        email: "debug@example.com",
        phone: "+971 50 123 4567",
        address_1: "Business Bay Tower",
        address_2: "Office 101",
        city: "Dubai",
        state: "Dubai",
        postcode: "00000",
        country: "UAE"
      },
      lineItems: [
        {
          id: "1",
          name: "Surge Espresso Blend (Debug)",
          weight: "250g",
          quantity: 2,
          price: 65,
          subtotal: 130,
          total: 130,
          tax: 0
        },
        {
          id: "2",
          name: "V60 Filter Papers",
          quantity: 1,
          price: 25,
          subtotal: 25,
          total: 25,
          tax: 0
        }
      ],
      subtotal: 155,
      tax: 7.75,
      taxLabel: "VAT (5%)",
      shipping: 15,
      shippingMethod: "delivery",
      discount: 0,
      total: 177.75,
      currency: "AED",
      currencySymbol: "AED",
      terms: "This is a debug preview generated by the server."
    }

    const pdfBuffer = await generateInvoicePDF(dummyData)

    return new NextResponse(Buffer.from(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'inline; filename="debug_invoice.pdf"',
      },
    })
  } catch (error) {
    console.error('Debug Preview Error:', error)
    return NextResponse.json({ error: 'Failed to generate preview' }, { status: 500 })
  }
}
