/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    admins: Admin;
    'app-categories': AppCategory;
    media: Media;
    'app-sub-categories': AppSubCategory;
    'customization-template': CustomizationTemplate;
    menu: Menu;
    shop: Shop;
    'shop-menu': ShopMenu;
    coupon: Coupon;
    'shop-coupon': ShopCoupon;
    otp: Otp;
    'app-cart': AppCart;
    wishlist: Wishlist;
    'app-orders': AppOrder;
    'web-categories': WebCategory;
    'web-sub-categories': WebSubCategory;
    'web-products': WebProduct;
    'web-cart': WebCart;
    'user-wt-coins': UserWtCoin;
    'web-orders': WebOrder;
    slots: Slot;
    'web-subscription': WebSubscription;
    'wt-stamps': WtStamp;
    'user-preferences': UserPreference;
    'app-contact-form': AppContactForm;
    'web-contact-form': WebContactForm;
    notifications: Notification;
    'app-best-seller': AppBestSeller;
    workshop: Workshop;
    blogs: Blog;
    wholesale: Wholesale;
    exports: Export;
    import_export_plugin_imports: ImportExportPluginImport;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'app-categories': AppCategoriesSelect<false> | AppCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'app-sub-categories': AppSubCategoriesSelect<false> | AppSubCategoriesSelect<true>;
    'customization-template': CustomizationTemplateSelect<false> | CustomizationTemplateSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    shop: ShopSelect<false> | ShopSelect<true>;
    'shop-menu': ShopMenuSelect<false> | ShopMenuSelect<true>;
    coupon: CouponSelect<false> | CouponSelect<true>;
    'shop-coupon': ShopCouponSelect<false> | ShopCouponSelect<true>;
    otp: OtpSelect<false> | OtpSelect<true>;
    'app-cart': AppCartSelect<false> | AppCartSelect<true>;
    wishlist: WishlistSelect<false> | WishlistSelect<true>;
    'app-orders': AppOrdersSelect<false> | AppOrdersSelect<true>;
    'web-categories': WebCategoriesSelect<false> | WebCategoriesSelect<true>;
    'web-sub-categories': WebSubCategoriesSelect<false> | WebSubCategoriesSelect<true>;
    'web-products': WebProductsSelect<false> | WebProductsSelect<true>;
    'web-cart': WebCartSelect<false> | WebCartSelect<true>;
    'user-wt-coins': UserWtCoinsSelect<false> | UserWtCoinsSelect<true>;
    'web-orders': WebOrdersSelect<false> | WebOrdersSelect<true>;
    slots: SlotsSelect<false> | SlotsSelect<true>;
    'web-subscription': WebSubscriptionSelect<false> | WebSubscriptionSelect<true>;
    'wt-stamps': WtStampsSelect<false> | WtStampsSelect<true>;
    'user-preferences': UserPreferencesSelect<false> | UserPreferencesSelect<true>;
    'app-contact-form': AppContactFormSelect<false> | AppContactFormSelect<true>;
    'web-contact-form': WebContactFormSelect<false> | WebContactFormSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'app-best-seller': AppBestSellerSelect<false> | AppBestSellerSelect<true>;
    workshop: WorkshopSelect<false> | WorkshopSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    wholesale: WholesaleSelect<false> | WholesaleSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    import_export_plugin_imports: ImportExportPluginImportsSelect<false> | ImportExportPluginImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'wt-coins': WtCoin;
    'ship-and-tax': ShipAndTax;
    'stamp-reward-products': StampRewardProduct;
  };
  globalsSelect: {
    'wt-coins': WtCoinsSelect<false> | WtCoinsSelect<true>;
    'ship-and-tax': ShipAndTaxSelect<false> | ShipAndTaxSelect<true>;
    'stamp-reward-products': StampRewardProductsSelect<false> | StampRewardProductsSelect<true>;
  };
  locale: null;
  user: User | Admin;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'customer';
  gender?: ('male' | 'female' | 'other') | null;
  phone?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  profileImage?: (number | null) | Media;
  /**
   * Automatically set when the user completes their first checkout.
   */
  stripeCustomerId?: string | null;
  addresses?:
    | {
        label?: string | null;
        addressFirstName?: string | null;
        addressLastName?: string | null;
        street?: string | null;
        apartment?: string | null;
        city?: string | null;
        emirates: 'abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah';
        country?: string | null;
        phoneNumber?: string | null;
        id?: string | null;
      }[]
    | null;
  pushToken?: string | null;
  /**
   * The unique code generated from the user’s first name.
   */
  referralCode?: string | null;
  referredBy?: (number | null) | User;
  referralCodeInput?: string | null;
  /**
   * Tracks the state of the referral reward for this user.
   */
  referralStatus?: ('pending' | 'rewarded' | 'not_eligible') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload media files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  role: 'super-admin' | 'admin' | 'shop-manager' | 'barista';
  name: string;
  gender?: ('male' | 'female' | 'other') | null;
  speciality?: string | null;
  shop?: (number | null) | Shop;
  profileImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop".
 */
export interface Shop {
  id: number;
  operationalSettings: {
    openingTime: string;
    closingTime: string;
    /**
     * Select which days the shop is open for business.
     */
    operatingDays?: {
      monday?: boolean | null;
      tuesday?: boolean | null;
      wednesday?: boolean | null;
      thursday?: boolean | null;
      friday?: boolean | null;
      saturday?: boolean | null;
      sunday?: boolean | null;
    };
  };
  address: {
    street?: string | null;
    apartment?: string | null;
    city?: string | null;
    emirates: 'abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah';
    /**
     * Country is fixed to UAE for this cafe group.
     */
    country?: string | null;
  };
  /**
   * Immediately opens/closes shop for customers.
   */
  isShopOpen?: boolean | null;
  shopManager: number | Admin;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-categories".
 */
export interface AppCategory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-sub-categories".
 */
export interface AppSubCategory {
  id: number;
  title: string;
  parentCategory?: (number | null) | AppCategory;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customization-template".
 */
export interface CustomizationTemplate {
  id: number;
  title: string;
  /**
   * Add sections for customization
   */
  sections?:
    | {
        title: string;
        selectionType: 'single' | 'multiple';
        groups?:
          | {
              groupTitle: string;
              options?:
                | {
                    label: string;
                    price?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        options?:
          | {
              label: string;
              price?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  name: string;
  /**
   * Keep it between 5 and 50 characters.
   */
  tagline?: string | null;
  /**
   * Upload Food Item Image
   */
  image?: (number | null) | Media;
  description?: string | null;
  category: number | AppCategory;
  subCategories?: (number | AppSubCategory)[] | null;
  regularPrice: number;
  salePrice?: number | null;
  /**
   * Select dietary type of the food item
   */
  dietaryType: 'veg' | 'non-veg' | 'vegan';
  customizations?:
    | {
        title?: string | null;
        template?: (number | null) | CustomizationTemplate;
        sections?:
          | {
              title: string;
              selectionType?: ('single' | 'multiple') | null;
              groups?:
                | {
                    groupTitle: string;
                    options?:
                      | {
                          label: string;
                          price?: number | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              options?:
                | {
                    label: string;
                    price?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-menu".
 */
export interface ShopMenu {
  id: number;
  name: string;
  shop?: (number | null) | Shop;
  menuRelation?: (number | Menu)[] | null;
  createdBy?: (number | null) | Admin;
  /**
   * Keep it between 5 and 50 characters.
   */
  tagline?: string | null;
  /**
   * Upload Food Item Image
   */
  image?: (number | null) | Media;
  description?: string | null;
  category: number | AppCategory;
  subCategories?: (number | AppSubCategory)[] | null;
  regularPrice: number;
  salePrice?: number | null;
  /**
   * Select dietary type of the food item
   */
  dietaryType?: ('veg' | 'non-veg' | 'vegan') | null;
  stockCount?: number | null;
  /**
   * Check if the item is in stock
   */
  inStock?: boolean | null;
  customizations?:
    | {
        title?: string | null;
        template?: (number | null) | CustomizationTemplate;
        sections?:
          | {
              title: string;
              selectionType?: ('single' | 'multiple') | null;
              groups?:
                | {
                    groupTitle: string;
                    options?:
                      | {
                          label: string;
                          price?: number | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              options?:
                | {
                    label: string;
                    price?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupon".
 */
export interface Coupon {
  id: number;
  /**
   * Unique code customers enter at checkout. Use uppercase letters and numbers only.
   */
  code: string;
  /**
   * Inactive coupons cannot be applied at checkout even if the code is correct.
   */
  couponStatus: 'active' | 'inactive';
  /**
   * Percentage deducts a % of the order total; Fixed Amount deducts a flat dollar value.
   */
  discountType: 'percentage' | 'fixed';
  discountAmount: number;
  /**
   * Choose whether this coupon applies to the entire cart or only specific products.
   */
  applicability: 'all' | 'products';
  /**
   * Coupon will be automatically invalidated after this date.
   */
  expiryDate: string;
  /**
   * Select the specific products or menu items this coupon applies to.
   */
  products?:
    | (
        | {
            relationTo: 'shop-menu';
            value: number | ShopMenu;
          }
        | {
            relationTo: 'web-products';
            value: number | WebProduct;
          }
      )[]
    | null;
  /**
   * Minimum cart total (in $) required to apply this coupon. Set to 0 for no minimum.
   */
  minimumAmount: number;
  /**
   * Max number of times this coupon can be used in total. Leave blank for unlimited.
   */
  usageLimit?: number | null;
  /**
   * Max number of times a single customer can use this coupon.
   */
  usageLimitPerUser: number;
  createdBy?: (number | null) | Admin;
  /**
   * Toggle on to show this coupon in "Available Offers".
   */
  isPubliclyVisible?: boolean | null;
  /**
   * Choose which platform(s) this coupon is valid on.
   */
  couponFor?: {
    /**
     * Check to enable this coupon on the website.
     */
    website?: boolean | null;
    /**
     * Check to enable this coupon on the mobile app.
     */
    app?: boolean | null;
  };
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-products".
 */
export interface WebProduct {
  id: number;
  name: string;
  tagline: string;
  hasVariantOptions?: boolean | null;
  variants?:
    | {
        variantName: string;
        variantImage: number | Media;
        hasVariantSub?: boolean | null;
        subscriptionDiscount?: number | null;
        subFreq?:
          | {
              duration: number;
              interval?: ('year' | 'month' | 'week' | 'day') | null;
              id?: string | null;
            }[]
          | null;
        variantRegularPrice: number;
        variantSalePrice?: number | null;
        variantInStock?: boolean | null;
        variantStockQuantity?: number | null;
        id?: string | null;
      }[]
    | null;
  regularPrice: number;
  salePrice?: number | null;
  inStock?: boolean | null;
  stockQuantity?: number | null;
  hasSimpleSub?: boolean | null;
  subscriptionDiscount?: number | null;
  /**
   * Add subscription frequency
   */
  subFreq?:
    | {
        duration: number;
        interval?: ('year' | 'month' | 'week' | 'day') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload product image that will be visible on Product Listing
   */
  productImage: number | Media;
  description: string;
  /**
   * Select category
   */
  categories: number | WebCategory;
  subCategories?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  farm: string;
  tastingNotes: string;
  variety: string;
  process: string;
  altitude: string;
  body: string;
  aroma: string;
  roast: string;
  finish: string;
  farmDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  videoBanner: number | Media;
  brewGuide?: {
    filter?: boolean | null;
    espresso?: boolean | null;
    milk?: boolean | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-categories".
 */
export interface WebCategory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-coupon".
 */
export interface ShopCoupon {
  id: number;
  /**
   * Unique code customers enter at checkout. Use uppercase letters and numbers only.
   */
  code: string;
  /**
   * Inactive coupons cannot be applied at checkout even if the code is correct.
   */
  couponStatus: 'active' | 'inactive';
  /**
   * Percentage deducts a % of the order total; Fixed Amount deducts a flat dollar value.
   */
  discountType: 'percentage' | 'fixed';
  discountAmount: number;
  /**
   * Choose whether this coupon applies to the entire cart or only specific products.
   */
  applicability: 'all' | 'products';
  /**
   * Coupon will be automatically invalidated after this date.
   */
  expiryDate: string;
  /**
   * Select the specific products or menu items this coupon applies to.
   */
  products?:
    | (
        | {
            relationTo: 'shop-menu';
            value: number | ShopMenu;
          }
        | {
            relationTo: 'web-products';
            value: number | WebProduct;
          }
      )[]
    | null;
  /**
   * Minimum cart total required to apply this coupon. Set to 0 for no minimum.
   */
  minimumAmount: number;
  /**
   * Max number of times this coupon can be used across all users.
   */
  usageLimit?: number | null;
  /**
   * Max number of times a single customer can use this coupon.
   */
  usageLimitPerUser: number;
  shop?: (number | null) | Shop;
  couponRelation: (number | Coupon)[];
  createdBy?: (number | null) | Admin;
  couponFor?: {
    website?: boolean | null;
    app?: boolean | null;
  };
  /**
   * Toggle on to show this coupon in "Available Offers".
   */
  isPubliclyVisible?: boolean | null;
  /**
   * Internal counter of how many times this coupon has been used.
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp".
 */
export interface Otp {
  id: number;
  email: string;
  otp: string;
  isUsed?: boolean | null;
  expiresAt: string;
  requestHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-cart".
 */
export interface AppCart {
  id: number;
  user: number | User;
  origin: 'cafe' | 'store';
  shop?: (number | null) | Shop;
  items?:
    | {
        product:
          | {
              relationTo: 'shop-menu';
              value: number | ShopMenu;
            }
          | {
              relationTo: 'web-products';
              value: number | WebProduct;
            };
        vId?: string | null;
        quantity?: number | null;
        /**
         * Snapshot of selections (sectionTitle, label, price).
         */
        customizations?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist".
 */
export interface Wishlist {
  id: number;
  user: number | User;
  items?:
    | {
        product:
          | {
              relationTo: 'shop-menu';
              value: number | ShopMenu;
            }
          | {
              relationTo: 'web-products';
              value: number | WebProduct;
            };
        shop?: (number | null) | Shop;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-orders".
 */
export interface AppOrder {
  id: number;
  user?: (number | null) | User;
  /**
   * Stored at checkout for guest-to-user linking.
   */
  email?: string | null;
  orderAcceptance: 'pending' | 'accepted' | 'rejected';
  appOrderStatus?: ('pending' | 'preparing' | 'pickup' | 'pickedup' | 'cancelled') | null;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refund-initiated' | 'refunded';
  shop: number | Shop;
  barista?: (number | null) | Admin;
  items: {
    product: number | ShopMenu;
    quantity?: number | null;
    customizations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  specialInstructions?: string | null;
  orderType: 'take-away' | 'dine-in';
  timeSelection?: ('now' | 'custom') | null;
  slot?: (number | null) | Slot;
  isCouponUsed?: boolean | null;
  coupon?: (number | null) | ShopCoupon;
  coinsUsed?: number | null;
  stampRewards?: (number | ShopMenu)[] | null;
  financials?: {
    /**
     * Sum of all item prices × quantities
     */
    subtotal?: number | null;
    /**
     * Discount applied via coupon code
     */
    couponDiscount?: number | null;
    /**
     * Discount applied via WT Coins redemption
     */
    wtCoinsDiscount?: number | null;
    /**
     * Tax applied on order total after discounts
     */
    taxAmount?: number | null;
    /**
     * Final amount charged to the customer (subtotal − discounts + tax)
     */
    total?: number | null;
  };
  stripeOrderId?: string | null;
  stripeData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define time slots for customer order bookings. Control availability and capacity per slot.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slots".
 */
export interface Slot {
  id: number;
  /**
   * Uncheck to temporarily pause bookings for this slot.
   */
  isActive?: boolean | null;
  /**
   * "Now" is auto-set to the current time on save. Only one slot collection-wide can use this mode.
   */
  timeSelection?: ('now' | 'custom') | null;
  /**
   * Select a fixed time in 30-minute increments.
   */
  slot?: string | null;
  /**
   * Total number of orders this slot can accept.
   */
  maxCapacity: number;
  /**
   * Live count of accepted orders. Updated automatically.
   */
  currentLoad?: number | null;
  /**
   * Auto-assigned based on your manager account.
   */
  shop?: (number | null) | Shop;
  /**
   * The manager who created this slot.
   */
  shopManager?: (number | null) | Admin;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sub-categories".
 */
export interface WebSubCategory {
  id: number;
  parentCategory: number | WebCategory;
  level1?:
    | {
        name: string;
        /**
         * Auto-generated from name
         */
        slug?: string | null;
        level2?:
          | {
              name: string;
              /**
               * Auto-generated from name
               */
              slug?: string | null;
              level3?:
                | {
                    name: string;
                    /**
                     * Auto-generated from name
                     */
                    slug?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-cart".
 */
export interface WebCart {
  id: number;
  user: number | User;
  items?:
    | {
        product: number | WebProduct;
        vId?: string | null;
        quantity?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aggregated User WT Coins Balance
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-wt-coins".
 */
export interface UserWtCoin {
  id: number;
  /**
   * User who owns this balance
   */
  user: number | User;
  /**
   * Current spendable balance
   */
  totalBalance?: number | null;
  /**
   * Log of all points earned
   */
  coinEarningHistory?:
    | {
        amount: number;
        earnedAt?: string | null;
        linkedOrder?:
          | ({
              relationTo: 'web-orders';
              value: number | WebOrder;
            } | null)
          | ({
              relationTo: 'app-orders';
              value: number | AppOrder;
            } | null);
        expiryDate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Log of all points spent
   */
  pointsRedemptionHistory?:
    | {
        redeemedPoints: number;
        associatedOrder:
          | {
              relationTo: 'web-orders';
              value: number | WebOrder;
            }
          | {
              relationTo: 'app-orders';
              value: number | AppOrder;
            };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-orders".
 */
export interface WebOrder {
  id: number;
  customerType?: ('guest' | 'user') | null;
  /**
   * Select the registered user account for this order.
   */
  user?: (number | null) | User;
  deliveryOption: 'delivery' | 'pickup';
  /**
   * The ID from Stripe
   */
  stripeOrderId?: string | null;
  origin: 'subscription' | 'one-time';
  /**
   * Stored at checkout for guest-to-user linking.
   */
  email?: string | null;
  items: {
    product: number | WebProduct;
    /**
     * The ID of the row in the Product Variants array
     */
    variantID: string;
    quantity: number;
    price: number;
    id?: string | null;
  }[];
  shippingAddress?: {
    addressFirstName?: string | null;
    addressLastName?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    emirates?: ('abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah') | null;
    phoneNumber?: string | null;
  };
  billingAddress?: {
    addressFirstName?: string | null;
    addressLastName?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    emirates?: ('abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah') | null;
    phoneNumber?: string | null;
  };
  paymentStatus: 'pending' | 'completed' | 'failed' | 'refund-initiated' | 'refunded';
  deliveryStatus?: ('placed' | 'shipped' | 'delivered' | 'cancelled') | null;
  couponCode?: (number | null) | Coupon;
  pointsUsed?: number | null;
  financials: {
    /**
     * Sum of all item prices × quantities
     */
    subtotal: number;
    /**
     * Discount applied via coupon code
     */
    couponDiscount?: number | null;
    /**
     * Discount applied via WT Coins redemption
     */
    wtCoinsDiscount?: number | null;
    /**
     * Shipping fee (0 for pickup orders)
     */
    shippingCharge?: number | null;
    /**
     * Tax applied on (subtotal − discounts + shipping)
     */
    taxAmount?: number | null;
    /**
     * Final amount charged (subtotal − discounts + shipping + tax)
     */
    total: number;
  };
  /**
   * Tracks if WTCoins have been awarded for this order
   */
  wtCoinsAwarded?: boolean | null;
  stripeData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-subscription".
 */
export interface WebSubscription {
  id: number;
  customerType?: ('guest' | 'user') | null;
  /**
   * Select the registered user account for this order.
   */
  user?: (number | null) | User;
  deliveryOption: 'delivery' | 'pickup';
  /**
   * The ID from Stripe
   */
  stripeSubscriptionID?: string | null;
  nextPaymentDate?: string | null;
  /**
   * Stored at checkout for guest-to-user linking.
   */
  email?: string | null;
  items: {
    product: number | WebProduct;
    /**
     * The ID of the row in the Product Variants array
     */
    variantID: string;
    /**
     * The ID of the row in the subFreq array
     */
    subFreqID: string;
    quantity: number;
    price: number;
    id?: string | null;
  }[];
  shippingAddress?: {
    addressFirstName?: string | null;
    addressLastName?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    emirates?: ('abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah') | null;
    phoneNumber?: string | null;
  };
  billingAddress?: {
    addressFirstName?: string | null;
    addressLastName?: string | null;
    addressLine1?: string | null;
    city?: string | null;
    emirates?: ('abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah') | null;
    phoneNumber?: string | null;
  };
  paymentStatus: 'pending' | 'completed' | 'failed';
  subsStatus?: ('active' | 'inactive' | 'cancelled') | null;
  pointsUsed?: number | null;
  financials: {
    /**
     * Product base price multiplied by quantity, before any discounts
     */
    subtotal: number;
    /**
     * Discount from the subscription plan percentage
     */
    subscriptionDiscount?: number | null;
    /**
     * Discount applied via WT Coins redemption
     */
    wtCoinsDiscount?: number | null;
    /**
     * Shipping fee (0 for pickup orders)
     */
    shippingCharge?: number | null;
    /**
     * Tax applied on (subtotal − discounts + shipping)
     */
    taxAmount?: number | null;
    /**
     * Final recurring amount charged (first payment may differ due to WT Coins)
     */
    total: number;
  };
  stripeData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  guestAccessToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wt-stamps".
 */
export interface WtStamp {
  id: number;
  user?: (number | null) | User;
  stampCount: number;
  stampReward: number;
  /**
   * Log of all stamps earned
   */
  stampEarningHistory?:
    | {
        stamps: number;
        earnedAt?: string | null;
        linkedOrder?:
          | ({
              relationTo: 'web-orders';
              value: number | WebOrder;
            } | null)
          | ({
              relationTo: 'app-orders';
              value: number | AppOrder;
            } | null);
        id?: string | null;
      }[]
    | null;
  /**
   * Log of all stamps spent
   */
  stampsRedemptionHistory?:
    | {
        redeemedStamps: number;
        associatedOrder:
          | {
              relationTo: 'web-orders';
              value: number | WebOrder;
            }
          | {
              relationTo: 'app-orders';
              value: number | AppOrder;
            };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stores per-user product customization preferences for the cafe app.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-preferences".
 */
export interface UserPreference {
  id: number;
  user: number | User;
  /**
   * Last-used customization selections per cafe menu product.
   */
  cafeProductPreferences?:
    | {
        /**
         * The shop-menu product ID this preference belongs to.
         */
        productId: string;
        /**
         * Snapshot of the last-used customization selections (sectionTitle, label, price).
         */
        customizations?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * When this preference was last saved.
         */
        savedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-contact-form".
 */
export interface AppContactForm {
  id: number;
  fullName: string;
  email: string;
  /**
   * Please select the type of inquiry for this ticket.
   */
  inquiryType:
    | 'order_issue'
    | 'payment_refund'
    | 'rewards_stamps'
    | 'barista_selection'
    | 'pickup_timing'
    | 'menu_availability'
    | 'other';
  phone: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-contact-form".
 */
export interface WebContactForm {
  id: number;
  fullName: string;
  email: string;
  /**
   * Please select the type of inquiry for this ticket.
   */
  inquiryType:
    | 'order_issue'
    | 'payment_refund'
    | 'rewards_stamps'
    | 'barista_selection'
    | 'pickup_timing'
    | 'menu_availability'
    | 'other';
  phone: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  notificationEnabled?: boolean | null;
  notifications?:
    | {
        title: string;
        description: string;
        origin: 'cafe' | 'store';
        notificationType: 'general' | 'order' | 'reward';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-best-seller".
 */
export interface AppBestSeller {
  id: number;
  shop: number | Shop;
  products: (number | ShopMenu)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop".
 */
export interface Workshop {
  id: number;
  title: string;
  workshopImage: number | Media;
  eventDate: string;
  calendyLink: string;
  eventTime: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage editorial articles for the company blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * This image appears at the top of the blog and in social share previews.
   */
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Select up to 3 other blogs to recommend to readers.
   */
  relatedBlogs?: (number | Blog)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Set a future date to automate when this post goes live on the website.
   */
  scheduledFor?: string | null;
  /**
   * Estimated minutes to read. Auto-calculated from content word count.
   */
  readTime?: number | null;
  /**
   * Mark this blog as featured.
   */
  isFeatured?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage and review wholesale partnership inquiries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wholesale".
 */
export interface Wholesale {
  id: number;
  email: string;
  phone: string;
  company: string;
  branch?: string | null;
  companyAddress: string;
  websiteInstagram?: string | null;
  /**
   * Categories selected by the business during submission.
   */
  business_info_group?: {
    office?: boolean | null;
    bakery?: boolean | null;
    coffee_shop?: boolean | null;
    restaurant?: boolean | null;
    other?: boolean | null;
    other_specification?: string | null;
  };
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format?: ('csv' | 'json') | null;
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import_export_plugin_imports".
 */
export interface ImportExportPluginImport {
  id: number;
  name?: string | null;
  collectionSlug: string;
  jsonData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'app-categories';
        value: number | AppCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'app-sub-categories';
        value: number | AppSubCategory;
      } | null)
    | ({
        relationTo: 'customization-template';
        value: number | CustomizationTemplate;
      } | null)
    | ({
        relationTo: 'menu';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'shop';
        value: number | Shop;
      } | null)
    | ({
        relationTo: 'shop-menu';
        value: number | ShopMenu;
      } | null)
    | ({
        relationTo: 'coupon';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'shop-coupon';
        value: number | ShopCoupon;
      } | null)
    | ({
        relationTo: 'otp';
        value: number | Otp;
      } | null)
    | ({
        relationTo: 'app-cart';
        value: number | AppCart;
      } | null)
    | ({
        relationTo: 'wishlist';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'app-orders';
        value: number | AppOrder;
      } | null)
    | ({
        relationTo: 'web-categories';
        value: number | WebCategory;
      } | null)
    | ({
        relationTo: 'web-sub-categories';
        value: number | WebSubCategory;
      } | null)
    | ({
        relationTo: 'web-products';
        value: number | WebProduct;
      } | null)
    | ({
        relationTo: 'web-cart';
        value: number | WebCart;
      } | null)
    | ({
        relationTo: 'user-wt-coins';
        value: number | UserWtCoin;
      } | null)
    | ({
        relationTo: 'web-orders';
        value: number | WebOrder;
      } | null)
    | ({
        relationTo: 'slots';
        value: number | Slot;
      } | null)
    | ({
        relationTo: 'web-subscription';
        value: number | WebSubscription;
      } | null)
    | ({
        relationTo: 'wt-stamps';
        value: number | WtStamp;
      } | null)
    | ({
        relationTo: 'user-preferences';
        value: number | UserPreference;
      } | null)
    | ({
        relationTo: 'app-contact-form';
        value: number | AppContactForm;
      } | null)
    | ({
        relationTo: 'web-contact-form';
        value: number | WebContactForm;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'app-best-seller';
        value: number | AppBestSeller;
      } | null)
    | ({
        relationTo: 'workshop';
        value: number | Workshop;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'wholesale';
        value: number | Wholesale;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'import_export_plugin_imports';
        value: number | ImportExportPluginImport;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'admins';
        value: number | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'admins';
        value: number | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  gender?: T;
  phone?: T;
  firstName?: T;
  lastName?: T;
  profileImage?: T;
  stripeCustomerId?: T;
  addresses?:
    | T
    | {
        label?: T;
        addressFirstName?: T;
        addressLastName?: T;
        street?: T;
        apartment?: T;
        city?: T;
        emirates?: T;
        country?: T;
        phoneNumber?: T;
        id?: T;
      };
  pushToken?: T;
  referralCode?: T;
  referredBy?: T;
  referralCodeInput?: T;
  referralStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  gender?: T;
  speciality?: T;
  shop?: T;
  profileImage?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-categories_select".
 */
export interface AppCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-sub-categories_select".
 */
export interface AppSubCategoriesSelect<T extends boolean = true> {
  title?: T;
  parentCategory?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customization-template_select".
 */
export interface CustomizationTemplateSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        title?: T;
        selectionType?: T;
        groups?:
          | T
          | {
              groupTitle?: T;
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    id?: T;
                  };
              id?: T;
            };
        options?:
          | T
          | {
              label?: T;
              price?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  image?: T;
  description?: T;
  category?: T;
  subCategories?: T;
  regularPrice?: T;
  salePrice?: T;
  dietaryType?: T;
  customizations?:
    | T
    | {
        title?: T;
        template?: T;
        sections?:
          | T
          | {
              title?: T;
              selectionType?: T;
              groups?:
                | T
                | {
                    groupTitle?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          price?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop_select".
 */
export interface ShopSelect<T extends boolean = true> {
  operationalSettings?:
    | T
    | {
        openingTime?: T;
        closingTime?: T;
        operatingDays?:
          | T
          | {
              monday?: T;
              tuesday?: T;
              wednesday?: T;
              thursday?: T;
              friday?: T;
              saturday?: T;
              sunday?: T;
            };
      };
  address?:
    | T
    | {
        street?: T;
        apartment?: T;
        city?: T;
        emirates?: T;
        country?: T;
      };
  isShopOpen?: T;
  shopManager?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-menu_select".
 */
export interface ShopMenuSelect<T extends boolean = true> {
  name?: T;
  shop?: T;
  menuRelation?: T;
  createdBy?: T;
  tagline?: T;
  image?: T;
  description?: T;
  category?: T;
  subCategories?: T;
  regularPrice?: T;
  salePrice?: T;
  dietaryType?: T;
  stockCount?: T;
  inStock?: T;
  customizations?:
    | T
    | {
        title?: T;
        template?: T;
        sections?:
          | T
          | {
              title?: T;
              selectionType?: T;
              groups?:
                | T
                | {
                    groupTitle?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          price?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupon_select".
 */
export interface CouponSelect<T extends boolean = true> {
  code?: T;
  couponStatus?: T;
  discountType?: T;
  discountAmount?: T;
  applicability?: T;
  expiryDate?: T;
  products?: T;
  minimumAmount?: T;
  usageLimit?: T;
  usageLimitPerUser?: T;
  createdBy?: T;
  isPubliclyVisible?: T;
  couponFor?:
    | T
    | {
        website?: T;
        app?: T;
      };
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-coupon_select".
 */
export interface ShopCouponSelect<T extends boolean = true> {
  code?: T;
  couponStatus?: T;
  discountType?: T;
  discountAmount?: T;
  applicability?: T;
  expiryDate?: T;
  products?: T;
  minimumAmount?: T;
  usageLimit?: T;
  usageLimitPerUser?: T;
  shop?: T;
  couponRelation?: T;
  createdBy?: T;
  couponFor?:
    | T
    | {
        website?: T;
        app?: T;
      };
  isPubliclyVisible?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp_select".
 */
export interface OtpSelect<T extends boolean = true> {
  email?: T;
  otp?: T;
  isUsed?: T;
  expiresAt?: T;
  requestHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-cart_select".
 */
export interface AppCartSelect<T extends boolean = true> {
  user?: T;
  origin?: T;
  shop?: T;
  items?:
    | T
    | {
        product?: T;
        vId?: T;
        quantity?: T;
        customizations?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist_select".
 */
export interface WishlistSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        shop?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-orders_select".
 */
export interface AppOrdersSelect<T extends boolean = true> {
  user?: T;
  email?: T;
  orderAcceptance?: T;
  appOrderStatus?: T;
  paymentStatus?: T;
  shop?: T;
  barista?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        customizations?: T;
        id?: T;
      };
  specialInstructions?: T;
  orderType?: T;
  timeSelection?: T;
  slot?: T;
  isCouponUsed?: T;
  coupon?: T;
  coinsUsed?: T;
  stampRewards?: T;
  financials?:
    | T
    | {
        subtotal?: T;
        couponDiscount?: T;
        wtCoinsDiscount?: T;
        taxAmount?: T;
        total?: T;
      };
  stripeOrderId?: T;
  stripeData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-categories_select".
 */
export interface WebCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sub-categories_select".
 */
export interface WebSubCategoriesSelect<T extends boolean = true> {
  parentCategory?: T;
  level1?:
    | T
    | {
        name?: T;
        slug?: T;
        level2?:
          | T
          | {
              name?: T;
              slug?: T;
              level3?:
                | T
                | {
                    name?: T;
                    slug?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-products_select".
 */
export interface WebProductsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  hasVariantOptions?: T;
  variants?:
    | T
    | {
        variantName?: T;
        variantImage?: T;
        hasVariantSub?: T;
        subscriptionDiscount?: T;
        subFreq?:
          | T
          | {
              duration?: T;
              interval?: T;
              id?: T;
            };
        variantRegularPrice?: T;
        variantSalePrice?: T;
        variantInStock?: T;
        variantStockQuantity?: T;
        id?: T;
      };
  regularPrice?: T;
  salePrice?: T;
  inStock?: T;
  stockQuantity?: T;
  hasSimpleSub?: T;
  subscriptionDiscount?: T;
  subFreq?:
    | T
    | {
        duration?: T;
        interval?: T;
        id?: T;
      };
  productImage?: T;
  description?: T;
  categories?: T;
  subCategories?: T;
  farm?: T;
  tastingNotes?: T;
  variety?: T;
  process?: T;
  altitude?: T;
  body?: T;
  aroma?: T;
  roast?: T;
  finish?: T;
  farmDescription?: T;
  videoBanner?: T;
  brewGuide?:
    | T
    | {
        filter?: T;
        espresso?: T;
        milk?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-cart_select".
 */
export interface WebCartSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        vId?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-wt-coins_select".
 */
export interface UserWtCoinsSelect<T extends boolean = true> {
  user?: T;
  totalBalance?: T;
  coinEarningHistory?:
    | T
    | {
        amount?: T;
        earnedAt?: T;
        linkedOrder?: T;
        expiryDate?: T;
        id?: T;
      };
  pointsRedemptionHistory?:
    | T
    | {
        redeemedPoints?: T;
        associatedOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-orders_select".
 */
export interface WebOrdersSelect<T extends boolean = true> {
  customerType?: T;
  user?: T;
  deliveryOption?: T;
  stripeOrderId?: T;
  origin?: T;
  email?: T;
  items?:
    | T
    | {
        product?: T;
        variantID?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        addressFirstName?: T;
        addressLastName?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        emirates?: T;
        phoneNumber?: T;
      };
  billingAddress?:
    | T
    | {
        addressFirstName?: T;
        addressLastName?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        emirates?: T;
        phoneNumber?: T;
      };
  paymentStatus?: T;
  deliveryStatus?: T;
  couponCode?: T;
  pointsUsed?: T;
  financials?:
    | T
    | {
        subtotal?: T;
        couponDiscount?: T;
        wtCoinsDiscount?: T;
        shippingCharge?: T;
        taxAmount?: T;
        total?: T;
      };
  wtCoinsAwarded?: T;
  stripeData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slots_select".
 */
export interface SlotsSelect<T extends boolean = true> {
  isActive?: T;
  timeSelection?: T;
  slot?: T;
  maxCapacity?: T;
  currentLoad?: T;
  shop?: T;
  shopManager?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-subscription_select".
 */
export interface WebSubscriptionSelect<T extends boolean = true> {
  customerType?: T;
  user?: T;
  deliveryOption?: T;
  stripeSubscriptionID?: T;
  nextPaymentDate?: T;
  email?: T;
  items?:
    | T
    | {
        product?: T;
        variantID?: T;
        subFreqID?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        addressFirstName?: T;
        addressLastName?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        emirates?: T;
        phoneNumber?: T;
      };
  billingAddress?:
    | T
    | {
        addressFirstName?: T;
        addressLastName?: T;
        addressLine1?: T;
        city?: T;
        emirates?: T;
        phoneNumber?: T;
      };
  paymentStatus?: T;
  subsStatus?: T;
  pointsUsed?: T;
  financials?:
    | T
    | {
        subtotal?: T;
        subscriptionDiscount?: T;
        wtCoinsDiscount?: T;
        shippingCharge?: T;
        taxAmount?: T;
        total?: T;
      };
  stripeData?: T;
  guestAccessToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wt-stamps_select".
 */
export interface WtStampsSelect<T extends boolean = true> {
  user?: T;
  stampCount?: T;
  stampReward?: T;
  stampEarningHistory?:
    | T
    | {
        stamps?: T;
        earnedAt?: T;
        linkedOrder?: T;
        id?: T;
      };
  stampsRedemptionHistory?:
    | T
    | {
        redeemedStamps?: T;
        associatedOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-preferences_select".
 */
export interface UserPreferencesSelect<T extends boolean = true> {
  user?: T;
  cafeProductPreferences?:
    | T
    | {
        productId?: T;
        customizations?: T;
        savedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-contact-form_select".
 */
export interface AppContactFormSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  inquiryType?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-contact-form_select".
 */
export interface WebContactFormSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  inquiryType?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  notificationEnabled?: T;
  notifications?:
    | T
    | {
        title?: T;
        description?: T;
        origin?: T;
        notificationType?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-best-seller_select".
 */
export interface AppBestSellerSelect<T extends boolean = true> {
  shop?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop_select".
 */
export interface WorkshopSelect<T extends boolean = true> {
  title?: T;
  workshopImage?: T;
  eventDate?: T;
  calendyLink?: T;
  eventTime?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  content?: T;
  relatedBlogs?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  scheduledFor?: T;
  readTime?: T;
  isFeatured?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wholesale_select".
 */
export interface WholesaleSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  company?: T;
  branch?: T;
  companyAddress?: T;
  websiteInstagram?: T;
  business_info_group?:
    | T
    | {
        office?: T;
        bakery?: T;
        coffee_shop?: T;
        restaurant?: T;
        other?: T;
        other_specification?: T;
      };
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import_export_plugin_imports_select".
 */
export interface ImportExportPluginImportsSelect<T extends boolean = true> {
  name?: T;
  collectionSlug?: T;
  jsonData?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * White Mantis Coins Configuration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wt-coins".
 */
export interface WtCoin {
  id: number;
  /**
   * Points to earn per order in percentage
   */
  pointsEarn: number;
  /**
   * Points to AED conversion rate in percentage
   */
  pointsToAed: number;
  /**
   * Reward expiry in months
   */
  rewardExpiry: number;
  /**
   * The maximum number of points a user can spend on a single order. Add 0 for no limit.
   */
  maxPointsPerOrder: number;
  /**
   * Minimum points a user must have to use them in an order. Add 0 for no limit.
   */
  minPointsPerOrder: number;
  /**
   * WTCoins awarded to the user who shared their referral code when the referred user completes their first order.
   */
  referralRewardForReferrer: number;
  /**
   * WTCoins awarded to the new user who used a referral code on their first order.
   */
  referralRewardForReferred: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-and-tax".
 */
export interface ShipAndTax {
  id: number;
  /**
   * Add tax percentage here (e.g., 5 for 5%)
   */
  tax?: number | null;
  /**
   * Add shipping charges for each emirate in AED
   */
  emirateCharges?: {
    abu_dhabi?: number | null;
    dubai?: number | null;
    sharjah?: number | null;
    ajman?: number | null;
    umm_al_quwain?: number | null;
    ras_al_khaimah?: number | null;
    fujairah?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Set the stamp reward products for the loyalty program.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stamp-reward-products".
 */
export interface StampRewardProduct {
  id: number;
  stampProducts: (number | ShopMenu)[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wt-coins_select".
 */
export interface WtCoinsSelect<T extends boolean = true> {
  pointsEarn?: T;
  pointsToAed?: T;
  rewardExpiry?: T;
  maxPointsPerOrder?: T;
  minPointsPerOrder?: T;
  referralRewardForReferrer?: T;
  referralRewardForReferred?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-and-tax_select".
 */
export interface ShipAndTaxSelect<T extends boolean = true> {
  tax?: T;
  emirateCharges?:
    | T
    | {
        abu_dhabi?: T;
        dubai?: T;
        sharjah?: T;
        ajman?: T;
        umm_al_quwain?: T;
        ras_al_khaimah?: T;
        fujairah?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stamp-reward-products_select".
 */
export interface StampRewardProductsSelect<T extends boolean = true> {
  stampProducts?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format?: ('csv' | 'json') | null;
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}