/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    admins: Admin;
    'app-categories': AppCategory;
    media: Media;
    'app-sub-categories': AppSubCategory;
    'customization-template': CustomizationTemplate;
    menu: Menu;
    shop: Shop;
    'shop-menu': ShopMenu;
    'surge-coupon': SurgeCoupon;
    'surge-shop-coupon': SurgeShopCoupon;
    otp: Otp;
    'app-cart': AppCart;
    wishlist: Wishlist;
    'app-orders': AppOrder;
    'web-categories': WebCategory;
    'web-sub-categories': WebSubCategory;
    'web-products': WebProduct;
    'web-cart': WebCart;
    'user-surge-coins': UserSurgeCoin;
    'web-orders': WebOrder;
    slots: Slot;
    'surge-stamps': SurgeStamp;
    'user-preferences': UserPreference;
    'app-contact-form': AppContactForm;
    'web-contact-form': WebContactForm;
    notifications: Notification;
    'app-best-seller': AppBestSeller;
    blogs: Blog;
    wholesale: Wholesale;
    'app-banners': AppBanner;
    newsletters: Newsletter;
    events: Event;
    'featured-news': FeaturedNew;
    careers: Career;
    'service-areas': ServiceArea;
    'coffee-packages': CoffeePackage;
    'addons-menu': AddonsMenu;
    exports: Export;
    import_export_plugin_imports: ImportExportPluginImport;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'app-categories': AppCategoriesSelect<false> | AppCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'app-sub-categories': AppSubCategoriesSelect<false> | AppSubCategoriesSelect<true>;
    'customization-template': CustomizationTemplateSelect<false> | CustomizationTemplateSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    shop: ShopSelect<false> | ShopSelect<true>;
    'shop-menu': ShopMenuSelect<false> | ShopMenuSelect<true>;
    'surge-coupon': SurgeCouponSelect<false> | SurgeCouponSelect<true>;
    'surge-shop-coupon': SurgeShopCouponSelect<false> | SurgeShopCouponSelect<true>;
    otp: OtpSelect<false> | OtpSelect<true>;
    'app-cart': AppCartSelect<false> | AppCartSelect<true>;
    wishlist: WishlistSelect<false> | WishlistSelect<true>;
    'app-orders': AppOrdersSelect<false> | AppOrdersSelect<true>;
    'web-categories': WebCategoriesSelect<false> | WebCategoriesSelect<true>;
    'web-sub-categories': WebSubCategoriesSelect<false> | WebSubCategoriesSelect<true>;
    'web-products': WebProductsSelect<false> | WebProductsSelect<true>;
    'web-cart': WebCartSelect<false> | WebCartSelect<true>;
    'user-surge-coins': UserSurgeCoinsSelect<false> | UserSurgeCoinsSelect<true>;
    'web-orders': WebOrdersSelect<false> | WebOrdersSelect<true>;
    slots: SlotsSelect<false> | SlotsSelect<true>;
    'surge-stamps': SurgeStampsSelect<false> | SurgeStampsSelect<true>;
    'user-preferences': UserPreferencesSelect<false> | UserPreferencesSelect<true>;
    'app-contact-form': AppContactFormSelect<false> | AppContactFormSelect<true>;
    'web-contact-form': WebContactFormSelect<false> | WebContactFormSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'app-best-seller': AppBestSellerSelect<false> | AppBestSellerSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    wholesale: WholesaleSelect<false> | WholesaleSelect<true>;
    'app-banners': AppBannersSelect<false> | AppBannersSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'featured-news': FeaturedNewsSelect<false> | FeaturedNewsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    'coffee-packages': CoffeePackagesSelect<false> | CoffeePackagesSelect<true>;
    'addons-menu': AddonsMenuSelect<false> | AddonsMenuSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    import_export_plugin_imports: ImportExportPluginImportsSelect<false> | ImportExportPluginImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'surge-coins': SurgeCoin;
    'ship-and-tax': ShipAndTax;
  };
  globalsSelect: {
    'surge-coins': SurgeCoinsSelect<false> | SurgeCoinsSelect<true>;
    'ship-and-tax': ShipAndTaxSelect<false> | ShipAndTaxSelect<true>;
  };
  locale: null;
  user: User | Admin;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: 'customer' | null;
  gender?: ('male' | 'female' | 'gender') | null;
  phone?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  profileImage?: (number | null) | Media;
  /**
   * Automatically set when the user completes their first checkout.
   */
  stripeCustomerId?: string | null;
  addresses?:
    | {
        label?: string | null;
        addressFirstName?: string | null;
        addressLastName?: string | null;
        street?: string | null;
        apartment?: string | null;
        city?: string | null;
        emirates?:
          | ('abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah')
          | null;
        country?: string | null;
        phoneNumber?: string | null;
        isDefaultAddress?: boolean | null;
        id?: string | null;
      }[]
    | null;
  pushToken?: string | null;
  /**
   * The unique code generated from the user’s first name.
   */
  referralCode?: string | null;
  referredBy?: (number | null) | User;
  referralCodeInput?: string | null;
  /**
   * Tracks the state of the referral reward for this user.
   */
  referralStatus?: ('pending' | 'rewarded' | 'not_eligible') | null;
  /**
   * Token used for generating user-specific barcodes in the mobile app.
   */
  barcodeToken?: string | null;
  /**
   * Apple unique user identifier (sub) from Sign in with Apple.
   */
  appleSubId?: string | null;
  /**
   * Whether the user signed in with an Apple private relay email.
   */
  isApplePrivateEmail?: boolean | null;
  /**
   * Real email for communications (order confirmations, notifications). Collected post-login from Apple users who used Hide My Email or phone number auth.
   */
  contactEmail?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage images
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  role: 'super-admin' | 'admin' | 'shop-manager' | 'barista';
  name: string;
  gender?: ('male' | 'female' | 'other') | null;
  speciality?: string | null;
  shop?: (number | null) | Shop;
  profileImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * Manage your cafe locations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop".
 */
export interface Shop {
  id: number;
  displayTitle?: string | null;
  operationalSettings: {
    openingTime: string;
    closingTime: string;
    /**
     * Select which days the shop is open for business.
     */
    operatingDays?: {
      monday?: boolean | null;
      tuesday?: boolean | null;
      wednesday?: boolean | null;
      thursday?: boolean | null;
      friday?: boolean | null;
      saturday?: boolean | null;
      sunday?: boolean | null;
    };
  };
  address: {
    street: string;
    apartment?: string | null;
    city?: string | null;
    emirates: 'abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah';
    /**
     * Country is fixed to UAE for this cafe group.
     */
    country?: string | null;
    /**
     * Decimal degrees, e.g. 25.2048
     */
    latitude?: number | null;
    /**
     * Decimal degrees, e.g. 55.2708
     */
    longitude?: number | null;
  };
  /**
   * Immediately opens/closes shop for customers.
   */
  isShopOpen?: boolean | null;
  shopManager: number | Admin;
  /**
   * The email of the admin who last updated this shop.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this shop.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Organize items into groups
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-categories".
 */
export interface AppCategory {
  id: number;
  title: string;
  image: number | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * The email of the admin who last updated this category.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this category.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * More specific groupings within a category
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-sub-categories".
 */
export interface AppSubCategory {
  id: number;
  title: string;
  parentCategory?: (number | null) | AppCategory;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * The email of the admin who last updated this sub-category.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this sub-category.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Sizes, add-ons, and modifiers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customization-template".
 */
export interface CustomizationTemplate {
  id: number;
  title: string;
  /**
   * Add sections for customization
   */
  sections?:
    | {
        title: string;
        selectionType: 'single' | 'multiple';
        groups?:
          | {
              groupTitle: string;
              options?:
                | {
                    label: string;
                    price?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        options?:
          | {
              label: string;
              price?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add or edit food & drink items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  name: string;
  /**
   * Keep it between 5 and 50 characters.
   */
  tagline?: string | null;
  /**
   * Upload Food Item Image
   */
  image?: (number | null) | Media;
  description?: string | null;
  category: number | AppCategory;
  subCategories?: (number | AppSubCategory)[] | null;
  regularPrice: number;
  salePrice?: number | null;
  /**
   * Select dietary type of the food item
   */
  dietaryType: 'veg' | 'non-veg' | 'vegan';
  customizations?:
    | {
        title?: string | null;
        template?: (number | null) | CustomizationTemplate;
        sections?:
          | {
              title: string;
              selectionType?: ('single' | 'multiple') | null;
              groups?:
                | {
                    groupTitle: string;
                    options?:
                      | {
                          label: string;
                          price?: number | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              options?:
                | {
                    label: string;
                    price?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable this to allow customers to earn a loyalty stamp when they purchase this item.
   */
  isStampEligible?: boolean | null;
  /**
   * Enable this if this item can be redeemed for free once a customer has collected enough stamps.
   */
  isStampFreeProduct?: boolean | null;
  /**
   * The email of the admin who last updated this item.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this item.
   */
  createdBy?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Mark this item as a latest/new arrival. Syncs to all linked shop menu items automatically.
   */
  isLatest?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-menu".
 */
export interface ShopMenu {
  id: number;
  _order?: string | null;
  name: string;
  shop: number | Shop;
  menuRelation?: (number | Menu)[] | null;
  createdBy?: (number | null) | Admin;
  /**
   * Keep it between 5 and 50 characters.
   */
  tagline?: string | null;
  /**
   * Upload Food Item Image
   */
  image?: (number | null) | Media;
  description?: string | null;
  category: number | AppCategory;
  subCategories?: (number | AppSubCategory)[] | null;
  regularPrice: number;
  salePrice?: number | null;
  /**
   * Select dietary type of the food item
   */
  dietaryType?: ('veg' | 'non-veg' | 'vegan') | null;
  stockCount?: number | null;
  /**
   * Check if the item is in stock
   */
  inStock?: boolean | null;
  /**
   * Synced automatically from Menu Builder and Customization Templates. Edit via the Menu Builder instead.
   */
  customizations?:
    | {
        title?: string | null;
        template?: (number | null) | CustomizationTemplate;
        sections?:
          | {
              title: string;
              selectionType?: ('single' | 'multiple') | null;
              groups?:
                | {
                    groupTitle: string;
                    options?:
                      | {
                          label: string;
                          price?: number | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              options?:
                | {
                    label: string;
                    price?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable to allow customers to earn a loyalty stamp when purchasing this item. (Admin only — synced from Menu)
   */
  isStampEligible?: boolean | null;
  /**
   * Enable if this item can be redeemed for free once a customer has collected enough stamps. (Admin only — synced from Menu)
   */
  isStampFreeProduct?: boolean | null;
  /**
   * The email of the admin who last updated this item.
   */
  lastUpdatedBy?: string | null;
  slug?: string | null;
  /**
   * Synced from Menu Builder. Only super-admins can override this directly on a shop item.
   */
  isLatest?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create and manage store discount codes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-coupon".
 */
export interface SurgeCoupon {
  id: number;
  /**
   * Unique code customers enter at checkout. Use uppercase letters and numbers only.
   */
  code: string;
  /**
   * Tagline to display on the coupon.
   */
  couponTagline: string;
  /**
   * Inactive coupons cannot be applied at checkout even if the code is correct.
   */
  couponStatus: 'active' | 'inactive';
  /**
   * Percentage deducts a % of the order total; Fixed Amount deducts a flat dollar value.
   */
  discountType: 'percentage' | 'fixed';
  discountAmount: number;
  /**
   * Choose whether this coupon applies to the entire cart or only specific products.
   */
  applicability: 'all' | 'products';
  /**
   * Coupon will be automatically invalidated after this date.
   */
  expiryDate: string;
  /**
   * Select the specific products or menu items this coupon applies to.
   */
  products?:
    | (
        | {
            relationTo: 'shop-menu';
            value: number | ShopMenu;
          }
        | {
            relationTo: 'web-products';
            value: number | WebProduct;
          }
      )[]
    | null;
  /**
   * Minimum cart total (in $) required to apply this coupon. Set to 0 for no minimum.
   */
  minimumAmount: number;
  /**
   * Max number of times this coupon can be used in total. Leave blank for unlimited.
   */
  usageLimit?: number | null;
  /**
   * Max number of times a single customer can use this coupon.
   */
  usageLimitPerUser: number;
  createdBy?: (number | null) | Admin;
  /**
   * Toggle on to show this coupon in "Available Offers".
   */
  isPubliclyVisible?: boolean | null;
  /**
   * Choose which platform(s) this coupon is valid on.
   */
  couponFor?: {
    /**
     * Check to enable this coupon on the website.
     */
    website?: boolean | null;
    /**
     * Check to enable this coupon on the mobile app.
     */
    app?: boolean | null;
  };
  usageCount?: number | null;
  /**
   * The email of the admin who last updated this coupon.
   */
  lastUpdatedBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Add, edit or remove products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-products".
 */
export interface WebProduct {
  id: number;
  _order?: string | null;
  name: string;
  tagline: string;
  /**
   * Choose the product type. Coffee fields appear for Beans/Drip Bags/Capsules; Merchandise fields appear for Mugs/Apparel/Equipment.
   */
  productType: 'coffee' | 'merchandise';
  hasVariantOptions?: boolean | null;
  variants?:
    | {
        /**
         * Add quantity in Grams
         */
        variantName: string;
        variantImage: number | Media;
        variantRegularPrice: number;
        variantSalePrice?: number | null;
        variantInStock?: boolean | null;
        variantStockQuantity?: number | null;
        id?: string | null;
      }[]
    | null;
  regularPrice: number;
  salePrice?: number | null;
  inStock?: boolean | null;
  stockQuantity?: number | null;
  /**
   * Upload product image that will be visible on Product Listing
   */
  productImage: number | Media;
  description: string;
  /**
   * Select category
   */
  categories: number | WebCategory;
  subCategories?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Group specific product details (e.g., Roast Type, Flavor Notes, Origin) into sections.
   */
  productHighlights?:
    | {
        sectionTitle: string;
        items?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  farm?: string | null;
  tastingNotes?: string | null;
  variety?: string | null;
  process?: string | null;
  altitude?: string | null;
  finish?: string | null;
  body?: string | null;
  aroma?: string | null;
  roast?: string | null;
  farmDescription?: string | null;
  videoBanner?: (number | null) | Media;
  brewGuide?: {
    filter?: boolean | null;
    espresso?: boolean | null;
    milk?: boolean | null;
  };
  material?: string | null;
  dimensions?: string | null;
  weight?: string | null;
  careInstructions?: string | null;
  recommendedProducts?: (number | WebProduct)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Mark this product as a latest/new arrival for the storefront.
   */
  isLatest?: boolean | null;
  /**
   * Mark this product as a bestseller for the storefront.
   */
  isBestseller?: boolean | null;
  /**
   * The email of the admin who last updated this product.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this product.
   */
  createdBy?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Organize products into groups
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-categories".
 */
export interface WebCategory {
  id: number;
  title: string;
  image: number | Media;
  brewingGuide?: {
    tabs?:
      | {
          tabName: string;
          /**
           * Upload video
           */
          video: number | Media;
          parameters: {
            label?: string | null;
            value: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[]
      | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * The email of the admin who last updated this category.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this category.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create and manage discount codes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-shop-coupon".
 */
export interface SurgeShopCoupon {
  id: number;
  /**
   * Unique code customers enter at checkout. Use uppercase letters and numbers only.
   */
  code: string;
  /**
   * Inactive coupons cannot be applied at checkout even if the code is correct.
   */
  couponStatus: 'active' | 'inactive';
  /**
   * Percentage deducts a % of the order total; Fixed Amount deducts a flat dollar value.
   */
  discountType: 'percentage' | 'fixed';
  discountAmount: number;
  /**
   * Choose whether this coupon applies to the entire cart or only specific products.
   */
  applicability: 'all' | 'products';
  /**
   * Coupon will be automatically invalidated after this date.
   */
  expiryDate: string;
  /**
   * Select the specific products or menu items this coupon applies to.
   */
  products?:
    | (
        | {
            relationTo: 'shop-menu';
            value: number | ShopMenu;
          }
        | {
            relationTo: 'web-products';
            value: number | WebProduct;
          }
      )[]
    | null;
  /**
   * Minimum cart total required to apply this coupon. Set to 0 for no minimum.
   */
  minimumAmount: number;
  /**
   * Max number of times this coupon can be used across all users.
   */
  usageLimit?: number | null;
  /**
   * Max number of times a single customer can use this coupon.
   */
  usageLimitPerUser: number;
  shop: number | Shop;
  couponRelation?: (number | SurgeCoupon)[] | null;
  createdBy?: (number | null) | Admin;
  couponFor?: {
    website?: boolean | null;
    app?: boolean | null;
  };
  /**
   * Toggle on to show this coupon in "Available Offers".
   */
  isPubliclyVisible?: boolean | null;
  /**
   * Internal counter of how many times this coupon has been used.
   */
  usageCount?: number | null;
  /**
   * The email of the admin who last updated this coupon.
   */
  lastUpdatedBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp".
 */
export interface Otp {
  id: number;
  email: string;
  otp: string;
  isUsed?: boolean | null;
  expiresAt: string;
  requestHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-cart".
 */
export interface AppCart {
  id: number;
  user: number | User;
  origin: 'cafe' | 'store';
  shop?: (number | null) | Shop;
  items?:
    | {
        product:
          | {
              relationTo: 'shop-menu';
              value: number | ShopMenu;
            }
          | {
              relationTo: 'web-products';
              value: number | WebProduct;
            };
        vId?: string | null;
        quantity?: number | null;
        /**
         * Snapshot of selections (sectionTitle, label, price).
         */
        customizations?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Group specific product details (e.g., Roast Type, Flavor Notes, Origin) into sections.
         */
        productHighlights?:
          | {
              sectionTitle: string;
              items?:
                | {
                    point: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * See what customers are saving
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist".
 */
export interface Wishlist {
  id: number;
  user: number | User;
  items?:
    | {
        product:
          | {
              relationTo: 'shop-menu';
              value: number | ShopMenu;
            }
          | {
              relationTo: 'web-products';
              value: number | WebProduct;
            };
        shop?: (number | null) | Shop;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * View and process incoming orders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-orders".
 */
export interface AppOrder {
  id: number;
  user?: (number | null) | User;
  /**
   * Stored at checkout for guest-to-user linking.
   */
  email?: string | null;
  orderAcceptance: 'pending' | 'accepted' | 'rejected';
  appOrderStatus?: ('pending' | 'preparing' | 'ready' | 'completed' | 'cancelled') | null;
  appOrderStatusDine?: ('pending' | 'preparing' | 'ready' | 'completed' | 'cancelled') | null;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refund-initiated' | 'refunded';
  refundReason?: string | null;
  refundedAmount?: number | null;
  shop: number | Shop;
  barista?: (number | null) | Admin;
  items: {
    product: number | ShopMenu;
    quantity?: number | null;
    customizations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  specialInstructions?: string | null;
  orderRating?: number | null;
  baristaRating?: number | null;
  orderType: 'take-away' | 'dine-in';
  timeSelection?: ('now' | 'custom') | null;
  slot?: (number | null) | Slot;
  isCouponUsed?: boolean | null;
  coupon?: (number | null) | SurgeShopCoupon;
  coinsUsed?: number | null;
  stampRewards?: (number | ShopMenu)[] | null;
  financials?: {
    /**
     * Sum of all item prices × quantities
     */
    subtotal?: number | null;
    /**
     * Discount applied via coupon code
     */
    couponDiscount?: number | null;
    /**
     * Discount applied via Surge Coins redemption
     */
    surgeCoinsDiscount?: number | null;
    /**
     * Tax applied on order total after discounts
     */
    taxAmount?: number | null;
    /**
     * Final amount charged to the customer (subtotal − discounts + tax)
     */
    total?: number | null;
  };
  stripeOrderId?: string | null;
  /**
   * Slot orders accepted more than 30 min before their slot time are held here. The cron job clears this flag at T-30 to release them into the Queued section.
   */
  scheduledForPrep?: boolean | null;
  /**
   * Flag to track if stamps have been awarded for this order to avoid double-crediting.
   */
  isStampsAwarded?: boolean | null;
  stripeData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  invoiceId?: string | null;
  invoiceDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Set pickup and delivery windows
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slots".
 */
export interface Slot {
  id: number;
  /**
   * Uncheck to temporarily pause bookings for this slot.
   */
  isActive?: boolean | null;
  /**
   * "Now" is auto-set to the current time on save. Only one slot collection-wide can use this mode.
   */
  timeSelection?: ('now' | 'custom') | null;
  /**
   * Select a fixed time in 30-minute increments.
   */
  slot?: string | null;
  /**
   * Total number of orders this slot can accept.
   */
  maxCapacity: number;
  /**
   * Live count of accepted orders. Updated automatically.
   */
  currentLoad?: number | null;
  /**
   * Auto-assigned for single-shop managers. Select your shop if you manage multiple.
   */
  shop?: (number | null) | Shop;
  /**
   * The manager who created this slot.
   */
  shopManager?: (number | null) | Admin;
  /**
   * The email of the admin who last updated this slot.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this slot.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * More specific product groupings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sub-categories".
 */
export interface WebSubCategory {
  id: number;
  parentCategory: number | WebCategory;
  level1?:
    | {
        name: string;
        level2?:
          | {
              name: string;
              level3?:
                | {
                    name: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The email of the admin who last updated this sub-category.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this sub-category.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Follow up on customers who didn't check out
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-cart".
 */
export interface WebCart {
  id: number;
  user: number | User;
  items?:
    | {
        product: number | WebProduct;
        vId?: string | null;
        quantity?: number | null;
        /**
         * Group specific product details (e.g., Roast Type, Flavor Notes, Origin) into sections.
         */
        productHighlights?:
          | {
              sectionTitle: string;
              items?:
                | {
                    point: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * View and adjust customer coin balances
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-surge-coins".
 */
export interface UserSurgeCoin {
  id: number;
  /**
   * User who owns this balance
   */
  user: number | User;
  /**
   * Current spendable balance (calculated from active earnings)
   */
  totalBalance?: number | null;
  /**
   * Log of all points earned
   */
  coinEarningHistory?:
    | {
        type?: ('offline' | 'online') | null;
        amount: number;
        /**
         * Points remaining from this earning that haven't expired or been used
         */
        remainingAmount: number;
        earnedAt?: string | null;
        linkedOrder?:
          | ({
              relationTo: 'web-orders';
              value: number | WebOrder;
            } | null)
          | ({
              relationTo: 'app-orders';
              value: number | AppOrder;
            } | null);
        offlineReferenceId?: string | null;
        expiryDate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Log of all points spent
   */
  pointsRedemptionHistory?:
    | {
        type?: ('offline' | 'online') | null;
        redeemedPoints: number;
        associatedOrder?:
          | ({
              relationTo: 'web-orders';
              value: number | WebOrder;
            } | null)
          | ({
              relationTo: 'app-orders';
              value: number | AppOrder;
            } | null);
        offlineReferenceId?: string | null;
        redeemedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * View and fulfill store orders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-orders".
 */
export interface WebOrder {
  id: number;
  customerType?: ('guest' | 'user') | null;
  /**
   * Select the registered user account for this order.
   */
  user?: (number | null) | User;
  /**
   * Stored at checkout for guest-to-user linking.
   */
  email?: string | null;
  deliveryOption: 'delivery' | 'pickup';
  origin: 'one-time';
  /**
   * The payment ID from Stripe
   */
  stripeOrderId?: string | null;
  /**
   * The shop location selected for pickup.
   */
  pickupShop?: (number | null) | Shop;
  items: {
    product: number | WebProduct;
    /**
     * The ID of the variation
     */
    variantID?: string | null;
    /**
     * The name of the variation
     */
    variantName?: string | null;
    quantity: number;
    price: number;
    productName?: string | null;
    /**
     * Group specific product details (e.g., Roast Type, Flavor Notes, Origin) into sections.
     */
    productHighlights?:
      | {
          sectionTitle: string;
          items?:
            | {
                point: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  shippingAddress?: {
    addressFirstName?: string | null;
    addressLastName?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    emirates?: ('abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah') | null;
    phoneNumber?: string | null;
    addressCountry?: string | null;
  };
  billingAddress?: {
    addressFirstName?: string | null;
    addressLastName?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    emirates?: ('abu_dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm_al_quwain' | 'ras_al_khaimah' | 'fujairah') | null;
    phoneNumber?: string | null;
    addressCountry?: string | null;
  };
  paymentStatus: 'pending' | 'completed' | 'failed' | 'refund-initiated' | 'refunded';
  deliveryStatus?: ('placed' | 'shipped' | 'delivered' | 'cancelled' | 'refund-initiated' | 'refunded') | null;
  deliveringBy?: string | null;
  deliveredOn?: string | null;
  /**
   * Mark when the order is packed and ready for customer pickup
   */
  isPickupReady?: boolean | null;
  pickedUpDate?: string | null;
  refundReason?: string | null;
  refundedOn?: string | null;
  refundedAmount?: number | null;
  couponCode?: (number | null) | SurgeCoupon;
  pointsUsed?: number | null;
  financials: {
    /**
     * Sum of all item prices × quantities
     */
    subtotal: number;
    /**
     * Shipping fee (0 for pickup orders)
     */
    shippingCharge?: number | null;
    /**
     * Discount applied via coupon code
     */
    couponDiscount?: number | null;
    /**
     * Discount applied via Surge Coins redemption
     */
    surgeCoinsDiscount?: number | null;
    /**
     * Tax rate applied on taxable amount
     */
    taxPercentage?: number | null;
    /**
     * Computed tax on (subtotal − discounts + shipping)
     */
    taxAmount?: number | null;
    /**
     * Final amount charged (subtotal − discounts + shipping + tax)
     */
    total: number;
  };
  /**
   * Tracks if WTCoins have been awarded for this order
   */
  wtCoinsAwarded?: boolean | null;
  orderRating?: number | null;
  stripeData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  guestAccessToken?: string | null;
  invoiceId?: string | null;
  invoiceDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage stamp card progress
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-stamps".
 */
export interface SurgeStamp {
  id: number;
  user?: (number | null) | User;
  stampCount: number;
  stampReward: number;
  /**
   * Log of all stamps earned
   */
  stampEarningHistory?:
    | {
        type?: ('offline' | 'online') | null;
        stamps: number;
        earnedAt?: string | null;
        linkedOrder?:
          | ({
              relationTo: 'web-orders';
              value: number | WebOrder;
            } | null)
          | ({
              relationTo: 'app-orders';
              value: number | AppOrder;
            } | null);
        offlineReferenceId?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Log of all stamps spent
   */
  stampsRedemptionHistory?:
    | {
        redeemedStamps: number;
        type?: ('offline' | 'online') | null;
        associatedOrder?:
          | ({
              relationTo: 'web-orders';
              value: number | WebOrder;
            } | null)
          | ({
              relationTo: 'app-orders';
              value: number | AppOrder;
            } | null);
        offlineReferenceId?: string | null;
        redeemedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stores per-user product customization preferences for the cafe app.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-preferences".
 */
export interface UserPreference {
  id: number;
  user: number | User;
  /**
   * Last-used customization selections per cafe menu product.
   */
  cafeProductPreferences?:
    | {
        /**
         * The shop-menu product ID this preference belongs to.
         */
        productId: string;
        /**
         * Snapshot of the last-used customization selections (sectionTitle, label, price).
         */
        customizations?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * When this preference was last saved.
         */
        savedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages received from the app
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-contact-form".
 */
export interface AppContactForm {
  id: number;
  fullName: string;
  email: string;
  /**
   * Please select the type of inquiry for this ticket.
   */
  inquiryType:
    | 'order_issue'
    | 'payment_refund'
    | 'rewards_stamps'
    | 'barista_selection'
    | 'pickup_timing'
    | 'menu_availability'
    | 'other';
  phone: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages received from the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-contact-form".
 */
export interface WebContactForm {
  id: number;
  fullName: string;
  email: string;
  /**
   * Please select the type of inquiry for this ticket.
   */
  inquiryType:
    | 'order_issue'
    | 'payment_refund'
    | 'rewards_stamps'
    | 'barista_selection'
    | 'pickup_timing'
    | 'menu_availability'
    | 'other';
  phone: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  notificationEnabled?: boolean | null;
  notifications?:
    | {
        title: string;
        description: string;
        origin: 'cafe' | 'store';
        notificationType: 'general' | 'order' | 'reward';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-best-seller".
 */
export interface AppBestSeller {
  id: number;
  shop: number | Shop;
  products?: (number | ShopMenu)[] | null;
  /**
   * The email of the admin who last updated this.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Publish articles and announcements
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  shortDescription: string;
  /**
   * This image appears at the top of the blog and in social share previews.
   */
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Select up to 3 other blogs to recommend to readers.
   */
  relatedBlogs?: (number | Blog)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Set a future date to automate when this post goes live on the website.
   */
  scheduledFor?: string | null;
  /**
   * Estimated minutes to read. Auto-calculated from content word count.
   */
  readTime?: number | null;
  /**
   * Mark this blog as featured.
   */
  isFeatured?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * The email of the admin who last updated this blog.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this blog.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Handle B2B and bulk orders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wholesale".
 */
export interface Wholesale {
  id: number;
  email: string;
  phone: string;
  company: string;
  branch?: string | null;
  companyAddress: string;
  websiteInstagram?: string | null;
  /**
   * Categories selected by the business during submission.
   */
  business_info_group?: {
    office?: boolean | null;
    bakery?: boolean | null;
    coffee_shop?: boolean | null;
    restaurant?: boolean | null;
    other?: boolean | null;
    other_specification?: string | null;
  };
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage homepage banners in the app
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-banners".
 */
export interface AppBanner {
  id: number;
  /**
   * Upload a banner image (images only — JPEG, PNG, WebP, etc.).
   */
  image: number | Media;
  /**
   * Select the page this banner belongs to. Each page can have at most 3 banners.
   */
  page: 'Home' | 'Cafe' | 'Store';
  updatedAt: string;
  createdAt: string;
}
/**
 * Send email updates to customers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  email: string;
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bookings received for Surge events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  eventDate: string;
  timeWindow: string;
  expectedGuests: number;
  eventType: 'private' | 'corporate';
  package: '30-cups' | '50-cups' | '100-cups' | 'additional-cups';
  addons?: string | null;
  city: string;
  emirate: 'dubai' | 'sharjah' | 'ras-al-khaimah' | 'ajman' | 'abu-dhabi';
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Featured news items managed exclusively from the admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-news".
 */
export interface FeaturedNew {
  id: number;
  title: string;
  description: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage job openings and career opportunities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  /**
   * Maximum 100 words.
   */
  title: string;
  /**
   * Maximum 500 words. Plain text only.
   */
  shortDescription: string;
  /**
   * Full URL where candidates can apply.
   */
  link: string;
  /**
   * The email of the admin who last updated this career listing.
   */
  lastUpdatedBy?: string | null;
  /**
   * The email of the admin who created this career listing.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Delivery locations and fees displayed on the events page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  _order?: string | null;
  location: string;
  /**
   * Enter 0 for free delivery.
   */
  fee: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Coffee packages displayed on the events page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coffee-packages".
 */
export interface CoffeePackage {
  id: number;
  _order?: string | null;
  name: string;
  features: {
    /**
     * e.g. "Coffee Setup", "Professional Barista"
     */
    value: string;
    id?: string | null;
  }[];
  servingOptions: {
    title: string;
    tiers: {
      /**
       * e.g. 50, 100, 150
       */
      cups: number;
      /**
       * e.g. 1500
       */
      price: number;
      id?: string | null;
    }[];
  };
  optionalAddOns: {
    title: string;
    items?:
      | {
          /**
           * e.g. "Extra Cups — AED 30/cup"
           */
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Add-on menu categories displayed on the events page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons-menu".
 */
export interface AddonsMenu {
  id: number;
  _order?: string | null;
  /**
   * e.g. "Coffee"
   */
  title: string;
  /**
   * e.g. "Small Bites / Canapés"
   */
  subtitle: string;
  /**
   * e.g. "Savoury selections crafted for elevated, memorable catering moments."
   */
  tagline: string;
  items: {
    /**
     * e.g. "Bruschetta Bites", "Tuna Crostini"
     */
    name: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format?: ('csv' | 'json') | null;
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import_export_plugin_imports".
 */
export interface ImportExportPluginImport {
  id: number;
  name?: string | null;
  collectionSlug: string;
  jsonData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'app-categories';
        value: number | AppCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'app-sub-categories';
        value: number | AppSubCategory;
      } | null)
    | ({
        relationTo: 'customization-template';
        value: number | CustomizationTemplate;
      } | null)
    | ({
        relationTo: 'menu';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'shop';
        value: number | Shop;
      } | null)
    | ({
        relationTo: 'shop-menu';
        value: number | ShopMenu;
      } | null)
    | ({
        relationTo: 'surge-coupon';
        value: number | SurgeCoupon;
      } | null)
    | ({
        relationTo: 'surge-shop-coupon';
        value: number | SurgeShopCoupon;
      } | null)
    | ({
        relationTo: 'otp';
        value: number | Otp;
      } | null)
    | ({
        relationTo: 'app-cart';
        value: number | AppCart;
      } | null)
    | ({
        relationTo: 'wishlist';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'app-orders';
        value: number | AppOrder;
      } | null)
    | ({
        relationTo: 'web-categories';
        value: number | WebCategory;
      } | null)
    | ({
        relationTo: 'web-sub-categories';
        value: number | WebSubCategory;
      } | null)
    | ({
        relationTo: 'web-products';
        value: number | WebProduct;
      } | null)
    | ({
        relationTo: 'web-cart';
        value: number | WebCart;
      } | null)
    | ({
        relationTo: 'user-surge-coins';
        value: number | UserSurgeCoin;
      } | null)
    | ({
        relationTo: 'web-orders';
        value: number | WebOrder;
      } | null)
    | ({
        relationTo: 'slots';
        value: number | Slot;
      } | null)
    | ({
        relationTo: 'surge-stamps';
        value: number | SurgeStamp;
      } | null)
    | ({
        relationTo: 'user-preferences';
        value: number | UserPreference;
      } | null)
    | ({
        relationTo: 'app-contact-form';
        value: number | AppContactForm;
      } | null)
    | ({
        relationTo: 'web-contact-form';
        value: number | WebContactForm;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'app-best-seller';
        value: number | AppBestSeller;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'wholesale';
        value: number | Wholesale;
      } | null)
    | ({
        relationTo: 'app-banners';
        value: number | AppBanner;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'featured-news';
        value: number | FeaturedNew;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'coffee-packages';
        value: number | CoffeePackage;
      } | null)
    | ({
        relationTo: 'addons-menu';
        value: number | AddonsMenu;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'import_export_plugin_imports';
        value: number | ImportExportPluginImport;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'admins';
        value: number | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'admins';
        value: number | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  gender?: T;
  phone?: T;
  firstName?: T;
  lastName?: T;
  profileImage?: T;
  stripeCustomerId?: T;
  addresses?:
    | T
    | {
        label?: T;
        addressFirstName?: T;
        addressLastName?: T;
        street?: T;
        apartment?: T;
        city?: T;
        emirates?: T;
        country?: T;
        phoneNumber?: T;
        isDefaultAddress?: T;
        id?: T;
      };
  pushToken?: T;
  referralCode?: T;
  referredBy?: T;
  referralCodeInput?: T;
  referralStatus?: T;
  barcodeToken?: T;
  appleSubId?: T;
  isApplePrivateEmail?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  gender?: T;
  speciality?: T;
  shop?: T;
  profileImage?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-categories_select".
 */
export interface AppCategoriesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  generateSlug?: T;
  slug?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-sub-categories_select".
 */
export interface AppSubCategoriesSelect<T extends boolean = true> {
  title?: T;
  parentCategory?: T;
  generateSlug?: T;
  slug?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customization-template_select".
 */
export interface CustomizationTemplateSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        title?: T;
        selectionType?: T;
        groups?:
          | T
          | {
              groupTitle?: T;
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    id?: T;
                  };
              id?: T;
            };
        options?:
          | T
          | {
              label?: T;
              price?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  image?: T;
  description?: T;
  category?: T;
  subCategories?: T;
  regularPrice?: T;
  salePrice?: T;
  dietaryType?: T;
  customizations?:
    | T
    | {
        title?: T;
        template?: T;
        sections?:
          | T
          | {
              title?: T;
              selectionType?: T;
              groups?:
                | T
                | {
                    groupTitle?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          price?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  isStampEligible?: T;
  isStampFreeProduct?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  generateSlug?: T;
  slug?: T;
  isLatest?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop_select".
 */
export interface ShopSelect<T extends boolean = true> {
  displayTitle?: T;
  operationalSettings?:
    | T
    | {
        openingTime?: T;
        closingTime?: T;
        operatingDays?:
          | T
          | {
              monday?: T;
              tuesday?: T;
              wednesday?: T;
              thursday?: T;
              friday?: T;
              saturday?: T;
              sunday?: T;
            };
      };
  address?:
    | T
    | {
        street?: T;
        apartment?: T;
        city?: T;
        emirates?: T;
        country?: T;
        latitude?: T;
        longitude?: T;
      };
  isShopOpen?: T;
  shopManager?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-menu_select".
 */
export interface ShopMenuSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  shop?: T;
  menuRelation?: T;
  createdBy?: T;
  tagline?: T;
  image?: T;
  description?: T;
  category?: T;
  subCategories?: T;
  regularPrice?: T;
  salePrice?: T;
  dietaryType?: T;
  stockCount?: T;
  inStock?: T;
  customizations?:
    | T
    | {
        title?: T;
        template?: T;
        sections?:
          | T
          | {
              title?: T;
              selectionType?: T;
              groups?:
                | T
                | {
                    groupTitle?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          price?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  isStampEligible?: T;
  isStampFreeProduct?: T;
  lastUpdatedBy?: T;
  slug?: T;
  isLatest?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-coupon_select".
 */
export interface SurgeCouponSelect<T extends boolean = true> {
  code?: T;
  couponTagline?: T;
  couponStatus?: T;
  discountType?: T;
  discountAmount?: T;
  applicability?: T;
  expiryDate?: T;
  products?: T;
  minimumAmount?: T;
  usageLimit?: T;
  usageLimitPerUser?: T;
  createdBy?: T;
  isPubliclyVisible?: T;
  couponFor?:
    | T
    | {
        website?: T;
        app?: T;
      };
  usageCount?: T;
  lastUpdatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-shop-coupon_select".
 */
export interface SurgeShopCouponSelect<T extends boolean = true> {
  code?: T;
  couponStatus?: T;
  discountType?: T;
  discountAmount?: T;
  applicability?: T;
  expiryDate?: T;
  products?: T;
  minimumAmount?: T;
  usageLimit?: T;
  usageLimitPerUser?: T;
  shop?: T;
  couponRelation?: T;
  createdBy?: T;
  couponFor?:
    | T
    | {
        website?: T;
        app?: T;
      };
  isPubliclyVisible?: T;
  usageCount?: T;
  lastUpdatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp_select".
 */
export interface OtpSelect<T extends boolean = true> {
  email?: T;
  otp?: T;
  isUsed?: T;
  expiresAt?: T;
  requestHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-cart_select".
 */
export interface AppCartSelect<T extends boolean = true> {
  user?: T;
  origin?: T;
  shop?: T;
  items?:
    | T
    | {
        product?: T;
        vId?: T;
        quantity?: T;
        customizations?: T;
        productHighlights?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    point?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist_select".
 */
export interface WishlistSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        shop?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-orders_select".
 */
export interface AppOrdersSelect<T extends boolean = true> {
  user?: T;
  email?: T;
  orderAcceptance?: T;
  appOrderStatus?: T;
  appOrderStatusDine?: T;
  paymentStatus?: T;
  refundReason?: T;
  refundedAmount?: T;
  shop?: T;
  barista?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        customizations?: T;
        id?: T;
      };
  specialInstructions?: T;
  orderRating?: T;
  baristaRating?: T;
  orderType?: T;
  timeSelection?: T;
  slot?: T;
  isCouponUsed?: T;
  coupon?: T;
  coinsUsed?: T;
  stampRewards?: T;
  financials?:
    | T
    | {
        subtotal?: T;
        couponDiscount?: T;
        surgeCoinsDiscount?: T;
        taxAmount?: T;
        total?: T;
      };
  stripeOrderId?: T;
  scheduledForPrep?: T;
  isStampsAwarded?: T;
  stripeData?: T;
  invoiceId?: T;
  invoiceDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-categories_select".
 */
export interface WebCategoriesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  brewingGuide?:
    | T
    | {
        tabs?:
          | T
          | {
              tabName?: T;
              video?: T;
              parameters?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  generateSlug?: T;
  slug?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sub-categories_select".
 */
export interface WebSubCategoriesSelect<T extends boolean = true> {
  parentCategory?: T;
  level1?:
    | T
    | {
        name?: T;
        level2?:
          | T
          | {
              name?: T;
              level3?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-products_select".
 */
export interface WebProductsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  tagline?: T;
  productType?: T;
  hasVariantOptions?: T;
  variants?:
    | T
    | {
        variantName?: T;
        variantImage?: T;
        variantRegularPrice?: T;
        variantSalePrice?: T;
        variantInStock?: T;
        variantStockQuantity?: T;
        id?: T;
      };
  regularPrice?: T;
  salePrice?: T;
  inStock?: T;
  stockQuantity?: T;
  productImage?: T;
  description?: T;
  categories?: T;
  subCategories?: T;
  productHighlights?:
    | T
    | {
        sectionTitle?: T;
        items?:
          | T
          | {
              point?: T;
              id?: T;
            };
        id?: T;
      };
  farm?: T;
  tastingNotes?: T;
  variety?: T;
  process?: T;
  altitude?: T;
  finish?: T;
  body?: T;
  aroma?: T;
  roast?: T;
  farmDescription?: T;
  videoBanner?: T;
  brewGuide?:
    | T
    | {
        filter?: T;
        espresso?: T;
        milk?: T;
      };
  material?: T;
  dimensions?: T;
  weight?: T;
  careInstructions?: T;
  recommendedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  isLatest?: T;
  isBestseller?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-cart_select".
 */
export interface WebCartSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        vId?: T;
        quantity?: T;
        productHighlights?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    point?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-surge-coins_select".
 */
export interface UserSurgeCoinsSelect<T extends boolean = true> {
  user?: T;
  totalBalance?: T;
  coinEarningHistory?:
    | T
    | {
        type?: T;
        amount?: T;
        remainingAmount?: T;
        earnedAt?: T;
        linkedOrder?: T;
        offlineReferenceId?: T;
        expiryDate?: T;
        id?: T;
      };
  pointsRedemptionHistory?:
    | T
    | {
        type?: T;
        redeemedPoints?: T;
        associatedOrder?: T;
        offlineReferenceId?: T;
        redeemedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-orders_select".
 */
export interface WebOrdersSelect<T extends boolean = true> {
  customerType?: T;
  user?: T;
  email?: T;
  deliveryOption?: T;
  origin?: T;
  stripeOrderId?: T;
  pickupShop?: T;
  items?:
    | T
    | {
        product?: T;
        variantID?: T;
        variantName?: T;
        quantity?: T;
        price?: T;
        productName?: T;
        productHighlights?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    point?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        addressFirstName?: T;
        addressLastName?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        emirates?: T;
        phoneNumber?: T;
        addressCountry?: T;
      };
  billingAddress?:
    | T
    | {
        addressFirstName?: T;
        addressLastName?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        emirates?: T;
        phoneNumber?: T;
        addressCountry?: T;
      };
  paymentStatus?: T;
  deliveryStatus?: T;
  deliveringBy?: T;
  deliveredOn?: T;
  isPickupReady?: T;
  pickedUpDate?: T;
  refundReason?: T;
  refundedOn?: T;
  refundedAmount?: T;
  couponCode?: T;
  pointsUsed?: T;
  financials?:
    | T
    | {
        subtotal?: T;
        shippingCharge?: T;
        couponDiscount?: T;
        surgeCoinsDiscount?: T;
        taxPercentage?: T;
        taxAmount?: T;
        total?: T;
      };
  wtCoinsAwarded?: T;
  orderRating?: T;
  stripeData?: T;
  guestAccessToken?: T;
  invoiceId?: T;
  invoiceDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slots_select".
 */
export interface SlotsSelect<T extends boolean = true> {
  isActive?: T;
  timeSelection?: T;
  slot?: T;
  maxCapacity?: T;
  currentLoad?: T;
  shop?: T;
  shopManager?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-stamps_select".
 */
export interface SurgeStampsSelect<T extends boolean = true> {
  user?: T;
  stampCount?: T;
  stampReward?: T;
  stampEarningHistory?:
    | T
    | {
        type?: T;
        stamps?: T;
        earnedAt?: T;
        linkedOrder?: T;
        offlineReferenceId?: T;
        id?: T;
      };
  stampsRedemptionHistory?:
    | T
    | {
        redeemedStamps?: T;
        type?: T;
        associatedOrder?: T;
        offlineReferenceId?: T;
        redeemedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-preferences_select".
 */
export interface UserPreferencesSelect<T extends boolean = true> {
  user?: T;
  cafeProductPreferences?:
    | T
    | {
        productId?: T;
        customizations?: T;
        savedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-contact-form_select".
 */
export interface AppContactFormSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  inquiryType?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-contact-form_select".
 */
export interface WebContactFormSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  inquiryType?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  notificationEnabled?: T;
  notifications?:
    | T
    | {
        title?: T;
        description?: T;
        origin?: T;
        notificationType?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-best-seller_select".
 */
export interface AppBestSellerSelect<T extends boolean = true> {
  shop?: T;
  products?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  featuredImage?: T;
  content?: T;
  relatedBlogs?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  scheduledFor?: T;
  readTime?: T;
  isFeatured?: T;
  generateSlug?: T;
  slug?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wholesale_select".
 */
export interface WholesaleSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  company?: T;
  branch?: T;
  companyAddress?: T;
  websiteInstagram?: T;
  business_info_group?:
    | T
    | {
        office?: T;
        bakery?: T;
        coffee_shop?: T;
        restaurant?: T;
        other?: T;
        other_specification?: T;
      };
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-banners_select".
 */
export interface AppBannersSelect<T extends boolean = true> {
  image?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  email?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phoneNumber?: T;
  eventDate?: T;
  timeWindow?: T;
  expectedGuests?: T;
  eventType?: T;
  package?: T;
  addons?: T;
  city?: T;
  emirate?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-news_select".
 */
export interface FeaturedNewsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  link?: T;
  lastUpdatedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  _order?: T;
  location?: T;
  fee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coffee-packages_select".
 */
export interface CoffeePackagesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  servingOptions?:
    | T
    | {
        title?: T;
        tiers?:
          | T
          | {
              cups?: T;
              price?: T;
              id?: T;
            };
      };
  optionalAddOns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons-menu_select".
 */
export interface AddonsMenuSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  subtitle?: T;
  tagline?: T;
  items?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import_export_plugin_imports_select".
 */
export interface ImportExportPluginImportsSelect<T extends boolean = true> {
  name?: T;
  collectionSlug?: T;
  jsonData?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Track coins earned and redeemed
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-coins".
 */
export interface SurgeCoin {
  id: number;
  /**
   * Points to earn per order in percentage
   */
  pointsEarn: number;
  /**
   * Points to AED conversion rate in percentage
   */
  pointsToAed: number;
  /**
   * Reward expiry in months
   */
  rewardExpiry: number;
  /**
   * The maximum number of points a user can spend on a single order. Add 0 for no limit.
   */
  maxPointsPerOrder: number;
  /**
   * Minimum points a user must have to use them in an order. Add 0 for no limit.
   */
  minPointsPerOrder: number;
  /**
   * WTCoins awarded to the user who shared their referral code when the referred user completes their first order.
   */
  referralRewardForReferrer: number;
  /**
   * WTCoins awarded to the new user who used a referral code on their first order.
   */
  referralRewardForReferred: number;
  /**
   * The email of the admin who last updated this configuration.
   */
  lastUpdatedBy?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-and-tax".
 */
export interface ShipAndTax {
  id: number;
  /**
   * Add tax percentage here (e.g., 5 for 5%)
   */
  tax?: number | null;
  /**
   * Add shipping charges for each emirate in AED
   */
  emirateCharges?: {
    abu_dhabi?: number | null;
    dubai?: number | null;
    sharjah?: number | null;
    ajman?: number | null;
    umm_al_quwain?: number | null;
    ras_al_khaimah?: number | null;
    fujairah?: number | null;
  };
  /**
   * Admin emails that receive a copy of every order confirmation. Maximum 5 recipients.
   */
  orderNotificationEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The email of the admin who last updated this configuration.
   */
  lastUpdatedBy?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surge-coins_select".
 */
export interface SurgeCoinsSelect<T extends boolean = true> {
  pointsEarn?: T;
  pointsToAed?: T;
  rewardExpiry?: T;
  maxPointsPerOrder?: T;
  minPointsPerOrder?: T;
  referralRewardForReferrer?: T;
  referralRewardForReferred?: T;
  lastUpdatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-and-tax_select".
 */
export interface ShipAndTaxSelect<T extends boolean = true> {
  tax?: T;
  emirateCharges?:
    | T
    | {
        abu_dhabi?: T;
        dubai?: T;
        sharjah?: T;
        ajman?: T;
        umm_al_quwain?: T;
        ras_al_khaimah?: T;
        fujairah?: T;
      };
  orderNotificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  lastUpdatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format?: ('csv' | 'json') | null;
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}